### ISSUE TITLE
Selinux depreciated selinux/flask.h and selinux/av_permissions.h 

### ISSUE THREAD

**Issue by rootinchase** [yo8192/fcron#10]
Failse to compile after selinux depreciated the following files:
- selinux/flask.h
- selinux/av_permissions.h 

Here is the commit that did it.
https://github.com/SELinuxProject/selinux/commit/76913d8adb61b5afe28fd3b4ce91feab29e284dd

In the commit they do say what to do instead.

To fix, replace flask.h calls with `string_to_security_class()`, and av_permissions.h  with `string_to_av_perm()`.

**Comment by yo8192** [comment]
Fixed with https://github.com/yo8192/fcron/pull/12
