### ISSUE TITLE
In file included from fcron.h:28,                  from fcron.c:25: global.h:48:10: fatal error: selinux/flask.h: No such file or directory    48 | #include <selinux/flask.h>       |          ^~~~~~~~~~~~~~~~~ compilation terminated. gmake: *** [Makefile:122: fcron.o] Error 1

### ISSUE THREAD

**Issue by Dylan700Manes** [yo8192/fcron#14]
#Linux ubuntu 5.8.0-1032-raspi #35-Ubuntu SMP PREEMPT Wed Jul 14 10:51:21 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
#fcron-3.2.1.src.tar.gz
#./compile
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gmake... /usr/bin/gmake
checking if make is actually GNU Make... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for strip... /usr/bin/strip
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking sys/fcntl.h usability... yes
checking sys/fcntl.h presence... yes
checking for sys/fcntl.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for strings.h... (cached) yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking security/pam_appl.h usability... no
checking security/pam_appl.h presence... no
checking for security/pam_appl.h... no
checking pam/pam_appl.h usability... no
checking pam/pam_appl.h presence... no
checking for pam/pam_appl.h... no
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking shadow.h usability... yes
checking shadow.h presence... yes
checking for shadow.h... yes
checking libaudit.h usability... no
checking libaudit.h presence... no
checking for libaudit.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for an ANSI C-conforming const... yes
checking for pid_t... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for uid_t in sys/types.h... yes
checking for ssize_t... yes
checking size of time_t... 8
checking size of pid_t... 4
checking size of time_t... (cached) 8
checking size of short int... 2
checking size of int... 4
checking size of long int... 8
checking size of long long int... 8
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking return type of signal handlers... void
checking for strftime... yes
checking for wait3 that fills in rusage... yes
checking for shutdown in -lxnet... no
checking for getcon in -lselinux... yes
checking for audit_open in -laudit... no
checking for a readline compatible library... -lreadline
checking readline.h usability... no
checking readline.h presence... no
checking for readline.h... no
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking whether readline supports history... yes
checking history.h usability... no
checking history.h presence... no
checking for history.h... no
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking for getloadavg... yes
checking for kstat_open in -lkstat... no
checking for getloadavg... (cached) yes
checking for pstat_getdynamic... no
checking for kstat_open in -lkstat... (cached) no
checking for getloadavg... (cached) yes
checking whether getloadavg requires setgid... no
checking function to use for lavg* options... getloadavg()
checking for getcwd... yes
checking for gettimeofday... yes
checking for mktime... yes
checking for putenv... yes
checking for strerror... yes
checking for setenv... yes
checking for unsetenv... yes
checking for gethostname... yes
checking for getopt_long... yes
checking for mkstemp... yes
checking for flock... yes
checking for lockf... yes
checking for setlinebuf... yes
checking for signal... yes
checking for sigset... yes
checking for gettimeofday... (cached) yes
checking for seteuid... yes
checking for setegid... yes
checking for setresuid... yes
checking for setresgid... yes
checking for setpriority... yes
checking for library containing getspnam... none required
checking for crypt... no
checking for crypt in -lcrypt... yes
checking for sa_len... no
checking cred.h usability... no
checking cred.h presence... no
checking for cred.h... no
checking sys/cred.h usability... no
checking sys/cred.h presence... no
checking for sys/cred.h... no
checking ucred.h usability... no
checking ucred.h presence... no
checking for ucred.h... no
checking sys/ucred.h usability... no
checking sys/ucred.h presence... no
checking for sys/ucred.h... no
checking for getpeerucred... no
checking for getpeereid... no
checking for sendmail... /usr/sbin/sendmail
checking actual sendmail to use... /usr/sbin/sendmail
checking for sh... /usr/bin/sh
checking default shell to use to run a job... /usr/bin/sh
checking for vi... /usr/bin/vi
checking editor to use for fcrontab... /usr/bin/vi
checking location of pid files... ${prefix}/var/run
checking location of fifo files... ${prefix}/var/run
checking location of spool directory... ${prefix}/var/spool/fcron
checking location of doc directory... ${datarootdir}/doc
checking for pkg-config... pkg-config
checking for systemd... yes
checking run non-privileged... no
checking if fcrondyn should be compiled... yes
checking root's username... root
checking root's groupname... root
checking username to run fcrontab under... fcron
checking groupname to run fcrontab under... fcron
checking use a system fcrontab... yes
checking install interactively a boot script... yes
checking automatic answer to make install's questions... no
checking if audit trails should be enabled if available... no
checking if pam should be used if available... yes
checking for pam_acct_mgmt in -lpam... no
checking if SELinux should be used... yes
checking for openjade... /usr/bin/openjade
checking for docbook2man... /usr/bin/docbook2man
checking Looking for docbook2man converter... default: /usr/bin/docbook2man
checking for nsgmls... no
checking for sgmlspl... /usr/bin/sgmlspl
checking Looking for docbook2man-spec file... default
checking Looking for dsssl stylsheets... default
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating doc/stylesheets/fcron-doc.dsl
config.status: creating config.h
config.status: config.h is unchanged

Summary :
-------

run in debug mode by default :      no
Audit trails :                      no
PAM :                               no
SELinux :                           yes
Readline :                          yes
Run without root's rights :         no
Load average support :              yes
compile fcrondyn :                  yes
fcron's user (resp. group) name :   fcron (resp. fcron)
sysfcrontab :                       yes (systab)
prefix:                             /usr/local
exec_prefix:                        ${prefix}
datarootdir:                        ${prefix}/share
bin dir:                            ${exec_prefix}/bin
sbin dir:                           ${exec_prefix}/sbin
spool dir:                          ${prefix}/var/spool/fcron
etc dir:                            ${prefix}/etc
doc dir:                            ${datarootdir}/doc
man dir:                            ${datarootdir}/man

You can now run '/usr/bin/gmake' to compile
and then (as root) '/usr/bin/gmake install' to install fcron.

gcc -O2 -Wall -I/usr/include/selinux  -DHAVE_CONFIG_H  -I. -I. -DPIDFILE="\"/usr/local/var/run/fcron.pid\"" -DREBOOT_LOCK="\"/usr/local/var/run/fcron.reboot\"" \
-DFIFOFILE="\"/usr/local/var/run/fcron.fifo\"" -DETC="\"/usr/local/etc\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DFCRON_CONF="\"fcron.conf\"" \
-DFCRONTABS="\"/usr/local/var/spool/fcron\"" \
-DFCRON_ALLOW="\"fcron.allow\"" -DFCRON_DENY="\"fcron.deny\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DSENDMAIL="\"/usr/sbin/sendmail\"" \
-DFCRON_EDITOR="\"/usr/bin/vi\"" -DBINDIREX="\"/usr/local/bin\"" \
-c fcron.c

In file included from fcron.h:28,
                 from fcron.c:25:
global.h:48:10: fatal error: selinux/flask.h: No such file or directory
   48 | #include <selinux/flask.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake: *** [Makefile:122: fcron.o] Error 1
#https://bugs.gentoo.org/772554

**Comment by yo8192** [comment]
It should be fixed in HEAD, can you try to clone the latest from GitHub
(not tagged in a release yet) and confirm if that works better?

**Comment by Dylan700Manes** [comment]
#fcron 3.3.0
./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gmake... /usr/bin/gmake
checking if make is actually GNU Make... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for strip... /usr/bin/strip
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking sys/fcntl.h usability... yes
checking sys/fcntl.h presence... yes
checking for sys/fcntl.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for strings.h... (cached) yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/timerfd.h usability... yes
checking sys/timerfd.h presence... yes
checking for sys/timerfd.h... yes
checking for sys/types.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking security/pam_appl.h usability... no
checking security/pam_appl.h presence... no
checking for security/pam_appl.h... no
checking pam/pam_appl.h usability... no
checking pam/pam_appl.h presence... no
checking for pam/pam_appl.h... no
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking shadow.h usability... yes
checking shadow.h presence... yes
checking for shadow.h... yes
checking libaudit.h usability... no
checking libaudit.h presence... no
checking for libaudit.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for an ANSI C-conforming const... yes
checking for pid_t... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for uid_t in sys/types.h... yes
checking for ssize_t... yes
checking size of time_t... 8
checking size of pid_t... 4
checking size of time_t... (cached) 8
checking size of short int... 2
checking size of int... 4
checking size of long int... 8
checking size of long long int... 8
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking return type of signal handlers... void
checking for strftime... yes
checking for wait3 that fills in rusage... yes
checking for shutdown in -lxnet... no
checking for getcon in -lselinux... yes
checking for audit_open in -laudit... no
checking for a readline compatible library... -lreadline
checking readline.h usability... no
checking readline.h presence... no
checking for readline.h... no
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking whether readline supports history... yes
checking history.h usability... no
checking history.h presence... no
checking for history.h... no
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking for getloadavg... yes
checking for kstat_open in -lkstat... no
checking for getloadavg... (cached) yes
checking for pstat_getdynamic... no
checking for kstat_open in -lkstat... (cached) no
checking for getloadavg... (cached) yes
checking whether getloadavg requires setgid... no
checking function to use for lavg* options... getloadavg()
checking for getcwd... yes
checking for gettimeofday... yes
checking for mktime... yes
checking for putenv... yes
checking for strerror... yes
checking for setenv... yes
checking for unsetenv... yes
checking for gethostname... yes
checking for getopt_long... yes
checking for mkstemp... yes
checking for flock... yes
checking for lockf... yes
checking for setlinebuf... yes
checking for signal... yes
checking for sigset... yes
checking for gettimeofday... (cached) yes
checking for seteuid... yes
checking for setegid... yes
checking for setresuid... yes
checking for setresgid... yes
checking for setpriority... yes
checking for library containing getspnam... none required
checking for crypt... no
checking for crypt in -lcrypt... yes
checking for sa_len... no
checking cred.h usability... no
checking cred.h presence... no
checking for cred.h... no
checking sys/cred.h usability... no
checking sys/cred.h presence... no
checking for sys/cred.h... no
checking ucred.h usability... no
checking ucred.h presence... no
checking for ucred.h... no
checking sys/ucred.h usability... no
checking sys/ucred.h presence... no
checking for sys/ucred.h... no
checking for getpeerucred... no
checking for getpeereid... no
checking for sendmail... /usr/sbin/sendmail
checking actual sendmail to use... /usr/sbin/sendmail
checking for sh... /usr/bin/sh
checking default shell to use to run a job... /usr/bin/sh
checking for vi... /usr/bin/vi
checking editor to use for fcrontab... /usr/bin/vi
checking location of pid files... ${prefix}/var/run
checking location of fifo files... ${prefix}/var/run
checking location of spool directory... ${prefix}/var/spool/fcron
checking location of doc directory... ${datarootdir}/doc
checking for pkg-config... pkg-config
checking for systemd... yes
checking run non-privileged... no
checking if fcrondyn should be compiled... yes
checking root's username... root
checking root's groupname... root
checking username to run fcrontab under... fcron
checking groupname to run fcrontab under... fcron
checking use a system fcrontab... yes
checking install interactively a boot script... yes
checking automatic answer to make install's questions... no
checking if audit trails should be enabled if available... no
checking if pam should be used if available... yes
checking for pam_acct_mgmt in -lpam... no
checking if SELinux should be used... yes
checking for openjade... /usr/bin/openjade
checking for docbook2man... /usr/bin/docbook2man
checking Looking for docbook2man converter... default: /usr/bin/docbook2man
checking for nsgmls... no
checking for sgmlspl... /usr/bin/sgmlspl
checking Looking for docbook2man-spec file... default
checking Looking for dsssl stylsheets... default
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating doc/stylesheets/fcron-doc.dsl
config.status: creating config.h

Summary :
-------

run in debug mode by default :      no
Audit trails :                      no
PAM :                               no
SELinux :                           yes
Readline :                          yes
Run without root's rights :         no
Load average support :              yes
compile fcrondyn :                  yes
fcron's user (resp. group) name :   fcron (resp. fcron)
sysfcrontab :                       yes (systab)
prefix:                             /usr/local
exec_prefix:                        ${prefix}
datarootdir:                        ${prefix}/share
bin dir:                            ${exec_prefix}/bin
sbin dir:                           ${exec_prefix}/sbin
spool dir:                          ${prefix}/var/spool/fcron
etc dir:                            ${prefix}/etc
doc dir:                            ${datarootdir}/doc
man dir:                            ${datarootdir}/man

You can now run '/usr/bin/gmake' to compile
and then (as root) '/usr/bin/gmake install' to install fcron.

•
•
•

make or gmake
gcc -O2 -Wall -I/usr/include/selinux  -DHAVE_CONFIG_H  -I. -I. -DPIDFILE="\"/usr/local/var/run/fcron.pid\"" -DREBOOT_LOCK="\"/usr/local/var/run/fcron.reboot\"" \
-DSUSPEND_FILE="\"/usr/local/var/run/fcron.suspend\"" -DFIFOFILE="\"/usr/local/var/run/fcron.fifo\"" -DETC="\"/usr/local/etc\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DFCRON_CONF="\"fcron.conf\"" \
-DFCRONTABS="\"/usr/local/var/spool/fcron\"" \
-DFCRON_ALLOW="\"fcron.allow\"" -DFCRON_DENY="\"fcron.deny\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DSENDMAIL="\"/usr/sbin/sendmail\"" \
-DFCRON_EDITOR="\"/usr/bin/vi\"" -DBINDIREX="\"/usr/local/bin\"" \
-c fcron.c
In file included from fcron.h:28,
                 from fcron.c:25:
global.h:48:10: fatal error: selinux/flask.h: No such file or directory
   48 | #include <selinux/flask.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by yo8192** [comment]
You are using 3.3.0.  Yes that version may not compile on newer system due to deprecation of a selinux header.  It was fixed in https://github.com/yo8192/fcron/commit/5f55e76fc1ab10a42b6407d7472811e1ee14440e#diff-c9848ba0b5db887a0fc07c2b9f605e3fba6eff9152037cb3d67775c0a5ff64e7 .

**Comment by Dylan700Manes** [comment]
I don't know what to do,
But by deleting the 2 lines of the file 
global.h
#include <selinux/flask.h>
#include <selinux/av_permissions.h>

by running ./configure; gmake afterwards;
I get:
gcc -O2 -Wall -I/usr/include/selinux  -DHAVE_CONFIG_H  -I. -I. -DPIDFILE="\"/usr/local/var/run/fcron.pid\"" -DREBOOT_LOCK="\"/usr/local/var/run/fcron.reboot\"" \
-DSUSPEND_FILE="\"/usr/local/var/run/fcron.suspend\"" -DFIFOFILE="\"/usr/local/var/run/fcron.fifo\"" -DETC="\"/usr/local/etc\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DFCRON_CONF="\"fcron.conf\"" \
-DFCRONTABS="\"/usr/local/var/spool/fcron\"" \
-DFCRON_ALLOW="\"fcron.allow\"" -DFCRON_DENY="\"fcron.deny\"" \
-DFCRON_SHELL="\"/usr/bin/sh\"" -DSENDMAIL="\"/usr/sbin/sendmail\"" \
-DFCRON_EDITOR="\"/usr/bin/vi\"" -DBINDIREX="\"/usr/local/bin\"" \
-c conf.c
In file included from fcron.h:28,
                 from conf.c:26:
global.h:195:5: warning: ‘security_context_t’ is deprecated [-Wdeprecated-declarations]
  195 |     security_context_t cf_user_context;
      |     ^~~~~~~~~~~~~~~~~~
global.h:196:5: warning: ‘security_context_t’ is deprecated [-Wdeprecated-declarations]
  196 |     security_context_t cf_file_context;
      |     ^~~~~~~~~~~~~~~~~~
conf.c: In function ‘read_file’:
conf.c:545:33: error: ‘SECCLASS_FILE’ undeclared (first use in this function)
  545 |                                 SECCLASS_FILE, FILE__ENTRYPOINT, &avd);
      |                                 ^~~~~~~~~~~~~
conf.c:545:33: note: each undeclared identifier is reported only once for each function it appears in
conf.c:545:48: error: ‘FILE__ENTRYPOINT’ undeclared (first use in this function)
  545 |                                SECCLASS_FILE, FILE__ENTRYPOINT, &avd);
      |                                               ^~~~~~~~~~~~~~~~

gmake: *** [Makefile:123: conf.o] Error 1

If this is normal, please do not answer
(I don't follow pro compilation)
Besides it is not my cup of coffee I always have problems^^
when it comes to this;) hope everything is good, goodbye
