### ISSUE TITLE
Delay job exicution.

### ISSUE THREAD

**Issue by 10maurycy10** [yo8192/fcron#18]
I have a job that requires the network to run, on a machine that suspends often. I have set it up with bootrun(true), but I want to add a set delay after startup to allow a network connection. Is this possible with fcron or do I have to make a custom script?

**Comment by yo8192** [comment]
There is not built-in perfect way, but below are a few ideas which may help.

If you mean to run it after a (re)boot of the machine, and use systemd, then you could change fcron's unit file to run after the "network-online" target, e.g.:
```After=remote-fs.target syslog.target time-sync.target network-online.target```
(disclaimer: I haven't tested this)

Alternatively, you could change fcron's `--firstsleep` command line arg.

If it is after resume that you want to run the job, one option would be to change your job command to something as:
```sleep 10 ; /your/command/line```
Of course that would delay all executions of the job, which may or may not be acceptable.

You could replace the sleep by a more clever script that checks if the network is online, or wait if not (you may find an existing one, or write your own), e.g. something as:
```script_to_wait_for_network_online --deadline 60 && /your/command/line```

**Comment by 10maurycy10** [comment]
> There is not built-in perfect way, but below are a few ideas which may help.
> 
> If you mean to run it after a (re)boot of the machine, and use systemd, then you could change fcron's unit file to run after the "network-online" target, e.g.: `After=remote-fs.target syslog.target time-sync.target network-online.target` (disclaimer: I haven't tested this)
This wont work with suspends 
> Alternatively, you could change fcron's `--firstsleep` command line arg.
> 
> If it is after resume that you want to run the job, one option would be to change your job command to something as: `sleep 10 ; /your/command/line` Of course that would delay all executions of the job, which may or may not be acceptable.
>
> You could replace the sleep by a more clever script that checks if the network is online, or wait if not (you may find an existing one, or write your own), e.g. something as: `script_to_wait_for_network_online --deadline 60 && /your/command/line`

I made a script that loops until the job return a 0 exit code.
