### ISSUE TITLE
Catch-22: documentation you need to read to figure out how to generate the documentation doesn't come pre-generated when you just git clone the repo??

### ISSUE THREAD

**Issue by dwawlyn** [yo8192/fcron#21]
For the github, the `README` just says:
```
See readme.txt in directory doc/en/txt/
 or readme.html in directory doc/en/HTML/.
```

I think this is a Catch-22?

That html documentation is what you need to read to figure out how to generate a bunch of stuff,
*including* the very documentation you need to read??

(It seems to only come with the `.sgml` files obviously accessible, and those are significantly harder to read in their raw form.)

So I ended up downloading:
http://fcron.free.fr/archives/fcron-3.2.1.src.tar.gz
from:
http://fcron.free.fr/download.php
cuz that was the easiest way to figure out how to use the git clone!

Thanks!

(
`fcron` is such a nice improvement on the more generally available defaults,
so I was hoping I might be able to help a little to make it more available on more distros.

(Specifically, I'm poking at getting it well-integrated into my opensuse tumbleweed install here.)
)

**Comment by yo8192** [comment]
Actually it did publish it now: https://yo8192.github.io/fcron/.
