### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [yo8192/fcron#22]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by yo8192** [comment]
Thanks for raising this.
The license was already present under doc/ (e.g. doc/en/gpl.html) and mentioned at the top of each file of code, but I take your point: I added a LICENSE file at the root of the repository to make it clearer and so github can automatically spot the license.
