### ISSUE TITLE
Are the Mailing Lists discontinued?

### ISSUE THREAD

**Issue by AndyM48** [yo8192/fcron#28]
Delivery to the following recipients failed permanently:

   * [fcronsupport-request@ml.free.fr](mailto:fcronsupport-request@ml.free.fr)

Where can I get help with fcron?

**Comment by yo8192** [comment]
Hi @AndyM48 ,

Indeed Free.fr has now stopped that service. Thanks for pointing that out: I'll update the website.

**Comment by AndyM48** [comment]
So where is the best place to get help with fcron?

**Comment by yo8192** [comment]
I've updated the Contact page now. I suggest trying a Linux forum on the web, or alternatively raise an issue here on GitHub.

The mailing lists were perhaps a little bit "old school" and had little traffic in recently, so I don't think it's worth opening new ones.

However I am open to suggestions if you have seen other projects use other simple-to-setup-and-maintain ways to do this.

**Comment by AndyM48** [comment]
Agreed, a forum would be ideal. I would start a reddit forum, but I don't know enough about fcron.
